#!/usr/bin/env python3
# Copyright (C) 2026 KersteinS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import argparse
import base64
import binascii
from collections import deque
import ipaddress
import os
import re
import shutil
import socket
import string
import subprocess
import sys
from typing import Self

# Enum Metadata
PROGRAM_NAME="dfw"
VERSION="0.0.3"

# Enum Logging
TRACE=5
DEBUG=10
INFO=20
WARNING=30
ERROR=40
CRITICAL=50

ALPHANUMERIC=string.ascii_lowercase + string.ascii_uppercase + string.digits

# Enum Paths
CONFIG_PATH="./etc/dfw/dfw.conf"
DFW_RULES_PATH="./etc/dfw/dfw.rules"

# Enum CommandArgs
CHAIN="DOCKER-USER"
RULE_COMMENT=f"{PROGRAM_NAME} ADDED RULE"

# Enum Errors
NOT_ROOT=1
FILE_MISSING=2
MISSING_MALFORMED_EDITS=3
MISSING_MALFORMED_BLOCK=4
CONFIG_EMPTY=5
CONFIG_INVALID=6
RULE_INVALID=7
IPTABLES_ERROR=8
CONFIRMATION_DENIED=9

RULES_HEAD= (
        "-A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n"
        "-A DOCKER-USER -i docker0 -j RETURN\n"
        "-A DOCKER-USER -s 172.17.0.0/12 -j RETURN\n"
        )
RULES_TAIL_DENY="-A DOCKER-USER -j DROP"
RULES_TAIL_ALLOW="-A DOCKER-USER -j RETURN"
DEFAULT_IFACE="eth0"

# -A DOCKER-USER -m conntrack --ctorigdstport 8080 -p tcp -j DROP
# To flush all DOCKER-USER chain rules: sudo iptables -F DOCKER-USER
# To list all DOCKER-USER chain rules: sudo iptables -L DOCKER-USER -n -v
# Goals: Script that accepts ufw-like syntax to add rules to iptables in the DOCKER-USER chain. Script is sole manager of DOCKER-USER chain. This allows rules to load before docker's default rules in iptables, (but still after docker's NAT changes the dest port to the container port but I work aroudn that)  effectively enabling firewall for docker using the host ports rather than the destination port (which is the other popular solution). Script should accept as many ufw-like commands as possible and support similar options when possible.
# Commands to support:
# enable                          enables the firewall
# disable                         disables the firewall
# default ARG                     set default policy
# logging LEVEL                   set logging to LEVEL
# allow ARGS                      add allow rule
# deny ARGS                       add deny rule
# reject ARGS                     add reject rule
# limit ARGS                      add limit rule
# delete RULE|NUM                 delete RULE
# insert NUM RULE                 insert RULE at NUM
# prepend RULE                    prepend RULE
# route RULE                      add route RULE # route is not supported since the only chain managed by dfw is DOCKER-USER. THere is no other traffic besides traffinc being routed to DOCKER-USER
# route delete RULE|NUM           delete route RULE # route is not supported since the only chain managed by dfw is DOCKER-USER. THere is no other traffic besides traffinc being routed to DOCKER-USER
# route insert NUM RULE           insert route RULE at NUM # route is not supported since the only chain managed by dfw is DOCKER-USER. THere is no other traffic besides traffic being routed to DOCKER-USER
# reload                          reload firewall
# reset                           reset firewall
# status                          show firewall status
# status numbered                 show firewall status as numbered list of RULES
# status verbose                  show verbose firewall status
# show ARG                        show firewall report
# version                         display version information

def to_base64(string: str) -> str:
    if not string:
        return ""
    return base64.urlsafe_b64encode(string.encode("utf-8")).decode("utf-8")

def from_base64(string: str) -> str:
    if not string:
        return ""
    try:
        return base64.urlsafe_b64decode(string.encode("utf-8")).decode("utf-8")
    except binascii.Error:
        log("Corrupted/Invalid encoded comment. Skipping", level=ERROR)
        return ""

def get_default_interface() -> str:
    with open("/proc/net/route") as file:
        for line in file.readlines():
            check = line.strip().split()
            if len(check) > 2 and check [1] == "00000000":
                return check[0]

class Rule:
    # TODO All rules need DFW_COMMENT: sudo iptables -A INPUT -p tcp --dport 22 -j RETURN -m comment --comment "DFW ADDED RULE"
    chain = ""
    invert_source_addr = False
    invert_dest_addr = False
    conntrack_mod = False
    limit_mod = False
    recent_mod = False
    conntrack_orig_dest_port = ""
    conntrack_state = ""
    limit_limit = ""
    limit_limit_burst = ""
    recent_set = False
    recent_update = False
    recent_seconds = ""
    recent_hitcount = ""
    recent_name = ""
    jump_target = ""

    # These are used for rule parsing in validate_and_normalize
    comment = ""
    modification = ""
    insert_index = ""
    delete_index = ""
    action = ""
    direction = ""
    output_interface = ""
    input_interface = ""
    log = ""
    dapp = ""
    ipv_type = ""
    source_addr = ""
    dest_addr = ""
    sapp = ""
    sports = ""
    dports = ""
    protocol = ""

    # note: app entries use ini-syntax like:
    #    [SomeService]
    #    title=Some title
    #    description=Some description
    #    ports=12/udp|34|56,78:90/tcp

    def parse_rule_ipt(self, line=""):
        # This takes an ipt command and parses it into a Rule instance
        if line == "":
            line = self.rule_text
        cmd = deque(line.split())
        junk = []
        invert_next_addr = False
        while cmd:
            i = cmd.popleft()
            log(f"{i=}", level=TRACE)
            if i in ("-A", "-D", "-I"):
                self.action = i
                j = cmd.popleft()
                if j == CHAIN:
                    self.chain = j
                else:
                    log(f"invalid chain provided: {j}", level=WARNING)
                    junk.append(j)
                    break
                if i == "-I":
                    if cmd[0].isdigit():
                        self.insert_index = cmd.popleft()
                    else:
                        self.insert_index = 1
                    continue
                if i == "-D":
                    if cmd[0].isdigit():
                        self.delete_index = cmd.popleft()
                        break
                    continue
                continue # -A has no special handling
            if i == CHAIN:
                self.chain = i
                continue
            if i == "-i":
                self.input_interface = cmd.popleft()
                continue
            if i == "-o":
                self.output_interface = cmd.popleft()
                continue
            if i == "!":
                invert_next_addr = True
                continue
            if i == "-s":
                self.source_addr = cmd.popleft()
                self.invert_source_addr = invert_next_addr
                invert_next_addr = False
                continue
            if i == "-d":
                self.dest_addr = cmd.popleft()
                self.invert_dest_addr = invert_next_addr
                invert_next_addr = False
                continue
            if i == "-p":
                self.protocol = cmd.popleft()
                continue
            if i == "--sport":
                self.sport = cmd.popleft()
                continue
            if i == "--dport":
                self.dport = cmd.popleft()
                continue
            # Unsuppported: --tcp-flags, --syn, --icmp-type
            if i == "-m":
                j = cmd.popleft()
                if j in ("conntrack", "limit", "recent", "multiport", "string", "iprange", "owner", "hashlimit"):
                    if j == "conntrack":
                        self.conntrack_mod = True
                        continue
                    if j == "limit":
                        self.limit_mod = True
                        continue
                    if j == "recent":
                        self.recent_mod = True
                        continue
                    log(f"module {j} not currently supported", level=WARNING)
                    junk.append(j)
                    continue
                log(f"Unrecognized module name: {j}", level=WARNING)
                continue
            if i in ("--ctstate", "--ctproto", "--ctorigsrc", "--ctorigdst", "--ctreplsrc", "--ctrepldst", "--ctorigsrcport", "--ctorigdstport", "--ctreplsrcport", "--ctrepldstport", "--ctstatus", "--ctexpire", "--ctdir"):
                if self.conntrack_mod is False:
                    log("Cannot enable conntrack module option without \"-m conntrack\" in command", level=WARNING)
                    junk.append(cmd.popleft())
                    continue
                if i == "--ctorigdstport":
                    self.conntrack_orig_dest_port = cmd.popleft()
                    continue
                if i == "--ctstate":
                    self.conntrack_state = cmd.popleft()
                    continue
                log(f"conntrack module flag not currently supported: {i}.", level=WARNING)
                junk.append(cmd.popleft())
                continue
            if i in ("--limit", "--limit-burst"):
                if self.limit_mod is False:
                    log("Cannot enable limit module option without \"-m limit\" in command", level=WARNING)
                    junk.append(cmd.popleft())
                    continue
                if i == "--limit":
                    self.limit_limit = cmd.popleft()
                    continue
                if i == "--limit-burst":
                    self.limit_limit_burst = cmd.popleft()
                continue
            if i in ("--set", "--rcheck", "--update", "--remove", "--seconds", "--hitcount", "--rttl","--reap", "--name", "--rsource", "--rdest", "--mask"):
                if self.recent_mod is False:
                    log("Cannot enable recent module option without \"-m recent\" in command", level=WARNING)
                    junk.append(cmd.popleft())
                    continue
                if i == "--set":
                    self.recent_set = True
                    continue
                if i == "--update":
                    self.recent_update = True
                    continue
                if i == "--seconds":
                    self.recent_seconds = cmd.popleft()
                    continue
                if i == "--hitcount":
                    self.recent_hitcount = cmd.popleft()
                    continue
                if i == "--name":
                    self.recent_name = cmd.popleft()
                    continue
                log(f"recent module flag not currently supported: {i}.", level=WARNING)
                # junk.append(cmd.popleft())
                continue
            if i == "-j":
                self.jump_target = cmd.popleft()
                continue
            junk.append(i)
        log(f"{junk=}", level=TRACE)
        if len(junk) != 0:
            log("Invalid iptables command!", level=ERROR)
        return

    @staticmethod
    def check_ports(ports_str):
        ports = ports_str.split(",")
        if len(ports) + ports_str.count(":") > 15:
            log(f"{len(ports)=}, {ports_str.count(':')=}", level=TRACE)
            raise ValueError(f"Bad port \"{ports_str}\"")
        for i in ports:
            if not i:
                log(f"{ports=}", level=TRACE)
                raise ValueError(f"Bad port \"{ports_str}\"")
            if ":" in i:
                check = [j for j in i.split(":") if len(j) > 0 and 0 < int(j) < 65536]
                if len(check) != 2 or  int(check[0]) > int(check[1]):
                    log(f"{check=}", level=TRACE)
                    raise ValueError(f"Bad port \"{ports_str}\"")
                for j in range(int(check[0])+1, int(check[1])):
                    check.insert(-1, str(j))
            elif not 0 < int(i) < 65536:
                log(f"{i=}", level=TRACE)
                raise ValueError(f"Bad port \"{ports_str}\"")

    @staticmethod
    def is_valid_ipv4(address: str):
        try:
            ipaddress.IPv4Address(address)
            return True
        except (ipaddress.AddressValueError, ValueError):
            log(f"{address} is not a vlid IPv4 address. Checking if it's a valid IPv4 network", level=TRACE)
            # pass
        try:
            ipaddress.IPv4Network(address, strict=False)
            return True
        except (ipaddress.AddressValueError, ipaddress.NetmaskValueError, ValueError):
            return False
    
    @staticmethod
    def is_valid_ipv6(address: str):
        try:
            ipaddress.IPv6Address(address)
            return True
        except (ipaddress.AddressValueError, ValueError):
            log(f"{address} is not a vlid IPv6 address. Checking if it's a valid IPv6 network", level=TRACE)
            # pass
        try:
            ipaddress.IPv6Network(address, strict=False)
            return True
        except (ipaddress.AddressValueError, ipaddress.NetmaskValueError, ValueError):
            return False

    @staticmethod
    def determine_service_port(service_name) -> str:
        try:
            return str(socket.getservbyname(service_name))
        except OSError:
            log(f"{service_name=} does not have a matching entry in /etc/services", level=TRACE)
            return ""

    @staticmethod
    def determine_service_proto(service_name) -> str:
        proto = ""
        try:
            socket.getservbyname(service_name)
        except OSError:
            log(f"{service_name=} does not have a matching entry in /etc/services", level=TRACE)
            return ""
        try:
            socket.getservbyname(service_name, "tcp")
            proto = "tcp"
        except OSError:
            log(f"{service_name=} does not have a matching tcp entry in /etc/services", level=TRACE)
            # pass
        try:
            socket.getservbyname(service_name, "udp")
            if proto:
                proto = "both"
            else:
                proto = "udp"
        except OSError:
            log(f"{service_name=} does not have a matching udp entry in /etc/services", level=TRACE)
            # pass
        return proto

    @staticmethod
    def check_comment(comment: str):
        if "'" in comment:
            log(f"{comment=}", level=TRACE)
            raise ValueError("Comment may not contain \"'\"")

    @staticmethod
    def check_insert_index(index: str):
        if not index.isdigit() or int(index)==0:
            raise ValueError(f"Cannot insert rule at position \"{index}\"")

    @staticmethod
    def check_action(action: str):
        if not action.lower() in ("allow", "deny", "reject", "limit"):
            log(f"{action=}", level=TRACE)
            raise ValueError("Invalid Syntax")

    @staticmethod
    def check_interface(interface: str):
        if "!" in interface:
            log(f"{interface=}", level=TRACE)
            raise ValueError("Bad interface name: reserved character: \"!\"")
        elif ":" in interface:
            log(f"{interface=}", level=TRACE)
            raise ValueError("Bad interface name: can't use interface aliases")
        elif interface in (".", ".."):
            log(f"{interface=}", level=TRACE)
            raise ValueError("Bad interface name: can't use \".\" or \"..\"")
        elif len(interface) > 15:
            log(f"{interface=}", level=TRACE)
            raise ValueError("Bad interface name: interface name is too long")
        elif not all(char in ALPHANUMERIC+"_-.+,=%@" for char in interface):
            log(f"{interface=}", level=TRACE)
            raise ValueError("Bad interface name")

    @staticmethod
    def is_numeric_port(port: str) -> bool:
        return all(char in string.digits+":," for char in port) and port[-1].isdigit() and port[0].isdigit()

    @staticmethod
    def check_supported_proto(proto: str):
        if proto not in ("tcp", "udp", "ipv6", "esp", "ah", "esp", "gre", "igmp", "vrrp"):
            raise ValueError(f"Unsupported protocol \"{proto}\"")

    @staticmethod
    def check_valid_port_protocol(proto: str):
        if proto not in ("tcp", "udp"):
            raise ValueError(f"Invalid port with protocol {proto}")

    @staticmethod
    def determine_ipvtype(source: str, dest: str):
            if source == dest:
                return source
            elif "both" not in (source, dest):
                log(f"{source=}, {dest=}", level=TRACE)
                raise ValueError("Mixed IP versions for from and to")
            elif source != "both":
                return source
            else: # therefore dest != "both"
                return dest

    @classmethod
    def parse_rule_command(cls, raw_command: str) -> Self:
        # This takes a dfw command (e.g. allow 8080) and parses it into a Rule instance
        # allow in on eth0 from 192.168.1.0/24 to any port 80 proto tcp
        # deny in on eth1 from 10.0.0.0/8 to any port 22 proto tcp
        # reject in on docker0 from 172.17.0.0/16 to any port 8080 proto tcp
        # limit in on eth0 from any to any port 22 proto tcp
        # allow 22
        # allow 80/tcp
        # allow 53/udp
        # allow 6000:6100/tcp
        # reject in 23
        # limit in 22/tcp
        # allow out 53/udp
        # deny out 25/tcp
        new_rule = Rule()
        is_advanced = False
        user_proto = ""
        user_dport = ""
        user_sport = ""
        to_service = ""
        from_service = ""
        cmd = raw_command.split()
        if len(cmd) < 2:
            log(f"{cmd=}, {len(cmd)=}", level=TRACE)
            raise ValueError("Invalid Syntax")
        if "comment" in cmd:
            loc = cmd.index("comment")
            if loc > len(cmd) - 2:
                log(f"{cmd=}, {len(cmd)=}", level=TRACE)
                raise ValueError("Option \"comment\" missing required argument")
            comment = cmd[loc+1:]
            if len(comment) < 2:
                check = comment[0]
            else:
                check = ' '.join(comment)
            cls.check_comment(check)
            new_rule.comment = to_base64(check)
            cmd = cmd[:loc] # discard "comment" and comment arg
        if cmd[0].lower() == "rule":
            cmd.pop(0)
        if len(cmd) < 2 or len(cmd) > 15:
            log(f"{cmd=}, {len(cmd)=}", level=TRACE)
            raise ValueError("Invalid Syntax")
        if cmd[0].lower() in ("prepend", "insert", "delete"):
            new_rule.modification = cmd.pop(0).lower()
        if new_rule.modification == "insert":
            if len(cmd) < 3:
                log(f"{cmd=}, {len(cmd)=}", level=TRACE)
                raise ValueError("Invalid Syntax")
            check = cmd.pop(0)
            cls.check_insert_index(check)
            new_rule.insert_index = check
        elif new_rule.modification == "delete":
            if len(cmd) == 1 and cmd[0].isdigit():
                new_rule.delete_index = cmd.pop(0)
                return new_rule
        if len(cmd) < 2:
            log(f"{cmd=}, {len(cmd)=}", level=TRACE)
            raise ValueError("Invalid Syntax")
        check = cmd.pop(0)
        cls.check_action(check)
        new_rule.action = check
        if len(cmd) < 1:
            log(f"{cmd=}, {len(cmd)=}", level=TRACE)
            raise ValueError("Invalid Syntax")
        if ("in" in cmd or "out" in cmd) and cmd[0].lower() not in ("in", "out"):
            raise ValueError("Invalid interface clause")
        elif "in" not in cmd and "out" not in cmd:
            new_rule.direction = "in"
        else:
            new_rule.direction = cmd.pop(0).lower()
            if len(cmd) < 1 or "in" in cmd or "out" in cmd:
                log(f"{cmd=}, {len(cmd)=}", level=TRACE)
                raise ValueError("Invalid interface clause")
            if cmd[0].lower() == "on":
                is_advanced = bool(cmd.pop(0)) # set is_advanced to True
                check = cmd.pop(0)
                cls.check_interface(check)
                if new_rule.direction == "out":
                    new_rule.output_interface = check
                else:
                    new_rule.input_interface = check
        # command could be done here. limit in on eth0
        if len(cmd) > 0:
            if cmd[0].lower() in ("log", "log-all") and len(cmd) > 1:
                new_rule.log = cmd.pop(0).lower()
            if "log" in cmd:
                raise ValueError("option \"log\" not allowed here")
            if "log-all" in cmd:
                raise ValueError("option \"log-all\" not allowed here")
        if len(cmd) == 1 and not is_advanced:
            # simple syntax, assumes direction is "in" (unless specified otherwise) and ports are dest ports or to_service/dapp
            if "/" in cmd[0]: # can't be an app if there's a /
                check = cmd[0].split("/")
                if len(check) != 2:# or not check[0] or not check[1]:
                    log(f"{cmd=}, {len(check)=}", level=TRACE)
                    raise ValueError("Bad port")
                user_port = check[0]
                user_proto = check[1]
            else:
                user_port = cmd[0]
            if user_proto:
                cls.check_supported_proto(user_proto)
                cls.check_valid_port_protocol(user_proto)
            if not user_port.isdigit() and user_port[0].isalnum() and all(char in ALPHANUMERIC+"_-.+" for char in user_port): # if True we're dealing with either a service or an application
                if user_proto == "": # if user proto is "" it could be either a service or application still
                    check = cls.determine_service_port(user_port)
                    if check:
                        to_service = user_port
                    elif user_port in cls.get_applications(): 
                        new_rule.dapp = user_port
                    else:
                        raise ValueError(f"Could not find a profile matching \"{user_port}\"")
                else: # it must be a service
                    check = cls.determine_service_port(user_port)
                    if check:
                        to_service = user_port
                    else:
                        log(f"{check=}, {len(check)=}", level=TRACE)
                        raise ValueError("Bad port")
            elif all(char in ALPHANUMERIC+",:" for char in user_port):
                if not cls.is_numeric_port(user_port):
                    log(f"{user_port=}", level=TRACE)
                    raise ValueError("Port ranges must be numeric")
                user_dport = user_port
            else:
                log(f"{user_port=}", level=TRACE)
                raise ValueError("Bad port")
            new_rule.ipv_type = "both"
        elif len(cmd) % 2 != 0:
            log(f"{cmd=}, {len(cmd)=}", level=TRACE)
            raise ValueError("Wrong number of arguments")
        elif "from" not in cmd and "to" not in cmd and not is_advanced:
            raise ValueError("Need \"to\" or \"from\" clause")
        else:
            # full syntax required
            # when using app in full syntax, ufw only refers to its applications.d configuration files 
            # and will not fall back on /etc/services. And when using port in full syntax, it can be either 
            # a port/port range or a service from /etc/services but not an app from applications.d.
            is_advanced = True
            valid_keys = ["proto", "from", "port", "app", "to"]
            key_dict = {
                    "proto": 0,
                    "from": 0,
                    "port": 0,
                    "app": 0,
                    "to": 0
                    }
            for i in cmd:
                if i in key_dict.keys():
                    key_dict[i] += 1
            if key_dict["proto"] > 1 or key_dict["from"] > 1 or key_dict["port"] > 2 or key_dict["app"] > 2 or key_dict["to"] > 1 or (key_dict["app"] > 0 and key_dict["proto"] > 0):
                log(f"{key_dict=}", level=TRACE)
                raise ValueError("Improper rule syntax")
            next_port_or_app = ""
            source_ipv_type = "both"
            dest_ipv_type = "both"
            while len(cmd) > 1:
                if cmd[0] not in valid_keys:
                    raise ValueError(f"Invalid token \"{cmd[0]}\"")
                elif cmd[0] == "proto":
                    del cmd[0] # discard "proto"
                    proto = cmd.pop(0) # retrieve proto value
                    cls.check_supported_proto(proto)
                    user_proto = proto
                elif cmd[0] in ("from", "to"):
                    direction = cmd.pop(0)
                    addr = cmd.pop(0)
                    ipv_type = ""
                    if addr == "any":
                        ipv_type = "both"
                    else:
                        if cls.is_valid_ipv4(addr):
                            ipv_type = "4"
                        elif cls.is_valid_ipv6(addr):
                            ipv_type = "6"
                        else:
                            log(f"{addr=}", level=TRACE)
                            raise ValueError("Bad source address")
                        if direction == "from":
                            new_rule.source_addr = addr
                        else:
                            new_rule.dest_addr = addr
                    if direction == "from":
                        source_ipv_type = ipv_type
                    else:
                        dest_ipv_type = ipv_type
                    if len(cmd) > 1 and cmd[0] in ("port", "app"): # look ahead for port or app
                        next_port_or_app = direction
                elif cmd[0] == "port" or cmd[0] == "app":
                    if next_port_or_app == "":
                        raise ValueError(f"Need \"from\" or \"to\" with \"{cmd[0]}\"")
                    key = cmd.pop(0)
                    value = cmd.pop(0)
                    if key == "app":
                        app = value
                        if next_port_or_app == "from":
                            new_rule.sapp = app
                        else:
                            new_rule.dapp = app
                        next_port_or_app = ""
                    else:
                        ports_str = value
                        ports = ports_str.split(",")
                        # value for port must be a service or port or port range. No / and protocol allowed.
                        if not cls.is_numeric_port(ports_str):
                            if "," in ports_str or ":" in ports_str:
                                log(f"{ports_str=} and cannot contain colon or comma", level=TRACE)
                                raise ValueError("Port ranges must be numeric")
                            if next_port_or_app == "from":
                                from_service = ports_str
                            else:
                                to_service = ports_str
                        elif next_port_or_app == "from":
                            user_sport = ports_str
                        else:
                            user_dport = ports_str
                        next_port_or_app = ""
            if user_proto and (user_dport != "" or user_sport != ""):
                cls.check_valid_port_protocol(user_proto)
            new_rule.ipv_type = cls.determine_ipvtype(source_ipv_type, dest_ipv_type)
        from_service_proto = "both"
        to_service_proto = "both"
        if user_sport:
            cls.check_ports(user_sport)
            new_rule.sports = user_sport
        elif from_service:
            new_rule.sports = cls.determine_service_port(from_service)
            if not new_rule.sports:
                raise ValueError(f"Bad port \"{from_service}\"")
            from_service_proto = cls.determine_service_proto(from_service)
            if from_service_proto != "both":
                cls.check_supported_proto(from_service_proto)
        if user_dport:
            try:
                cls.check_ports(user_dport)
                new_rule.dports = user_dport
            except ValueError:
                if not is_advanced:
                    raise ValueError("Bad port")
                else:
                    raise
        elif to_service:
            new_rule.dports = cls.determine_service_port(to_service)
            if not new_rule.dports and not is_advanced:
                raise ValueError("Bad port")
            elif not new_rule.dports:
                raise ValueError(f"Bad port \"{to_service}\"")
            to_service_proto = cls.determine_service_proto(to_service)
            if to_service_proto != "both":
                cls.check_supported_proto(to_service_proto)
        if to_service or from_service:
            if from_service_proto == to_service_proto:
                new_rule.protocol = from_service_proto
            elif "both" not in (from_service_proto, to_service_proto):
                log(f"{from_service_proto=}, {to_service_proto=}", level=TRACE)
                raise ValueError("Protocol mismatch (from/to)")
            elif from_service_proto != "both":
                new_rule.protocol = from_service_proto
            else: # therefore to_service_proto != "both"
                new_rule.protocol = to_service_proto
            if new_rule.protocol != "both" and user_proto and new_rule.protocol != user_proto:
                log(f"{new_rule.protocol=}, {user_proto=}", level=TRACE)
                raise ValueError(f"Protocol mismatch with specified protocol {user_proto}")
            elif new_rule.protocol == "both" and user_proto:
                new_rule.protocol = user_proto
        elif user_proto:
            new_rule.protocol = user_proto
        elif not is_advanced:
            new_rule.protocol = "both"
        else:
            new_rule.protocol = "any"
        if any(i in (":",",") for i in new_rule.sports+new_rule.dports):
            # multiple ports detected. Must specify tcp or udp explicitly
            if new_rule.protocol in ("any", "both"):
                log(f"{new_rule.protocol=}", level=TRACE)
                raise ValueError("Must specify \"tcp\" or \"udp\" with multiple ports")
            elif new_rule.protocol not in ("tcp", "udp"):
                log(f"{new_rule.protocol=}", level=TRACE)
                raise ValueError("Bad port")
        if new_rule.sapp or new_rule.dapp:
            log(f"{new_rule.sapp=}, {new_rule.dapp=}", level=TRACE)
            raise ValueError("Application Integration not currently supported") # TODO
        return new_rule

    def print_rule_form(self) -> str:
        """Form pattern: action[_logtype] protocol ipv_type source_addr source_ports dest_addr dest_ports [sapp dapp] direction[_interface] [comment]"""
        output = "[RULEFORM] "
        logtype = f"_{self.log}" if self.log else ""
        proto = "tcp/udp" if self.protocol == "both" else self.protocol
        ipv_type = f"ipv{self.ipv_type}" if self.ipv_type != "both" else "both"
        source_addr = self.source_addr if self.source_addr else "any"
        dest_addr = self.dest_addr if self.dest_addr else "any"
        sports = self.sports if self.sports else "any"
        dports = self.dports if self.dports else "any"
        sapp = ""
        dapp = ""
        if self.sapp or self.dapp:
            sapp = self.sapp.replace(" ", "%20") + " " if self.sapp else "- "
            dapp = self.dapp.replace(" ", "%20") + " " if self.dapp else "- "
        if self.direction == "out":
            direction_interface = f"out_{self.output_interface}" if self.output_interface else "out"
        else:
            direction_interface = f"in_{self.input_interface}" if self.input_interface else "in"
        comment = f"comment={self.comment}" if self.comment else ""
        output+=f"{self.action}{logtype} {proto} {ipv_type} {source_addr} {sports} {dest_addr} {dports} {sapp}{dapp}{direction_interface} {comment}"
        return output

    @classmethod
    def parse_rule_form(cls, form: str):
        """Form pattern: action[_logtype] protocol ipv_type source_addr source_ports dest_addr dest_ports [sapp dapp] direction[_interface] [comment]"""
        errormsg = f"Invalid RULEFORM: {form}"
        new_rule = Rule("", "")
        parts = form.split()[1:] # immediately discard "[RULEFORM]"
        if not 7 < len(parts) < 12:
            log(f"{parts=}, {len(parts)=}", level=TRACE)
            raise ValueError(errormsg)
        if "comment=" in parts[-1]:
            new_rule.comment = parts.pop(-1).replace("comments=", "")
        if "_" in parts[0]:
            action,logtype = parts.pop(0).split("_")
        else:
            action,logtype = parts.pop(0),""
        try: 
            cls.check_action(action)
            new_rule.action = action
        except ValueError:
            log(f"{action=}", level=TRACE)
            raise ValueError(errormsg)
        if logtype not in ("", "log", "log-all"):
            log(f"{logtype=}", level=TRACE)
            raise ValueError(errormsg)
        if logtype:
            new_rule.log = logtype
        proto = parts.pop(0)
        if proto != "tcp/udp":
            if proto != "any":
                try:
                    cls.check_supported_proto(proto)
                except ValueError:
                    log(f"{proto=}", level=TRACE)
                    raise ValueError(errormsg)
            new_rule.protocol = proto
        else:
            new_rule.protocol = "both"
        ipv_type = parts.pop(0)
        if ipv_type not in ("both", "ipv4", "ipv6"):
            log(f"{ipv_type=}", level=TRACE)
            raise ValueError(errormsg)
        new_rule.ipv_type = ipv_type.replace("ipv", "")
        source_addr = parts.pop(0)
        if not (source_addr == "any" or cls.is_valid_ipv4(source_addr) or cls.is_valid_ipv6(source_addr)):
            log(f"{source_addr=}", level=TRACE)
            raise ValueError(errormsg)
        if source_addr != "any":
            new_rule.source_addr = source_addr
        source_ports = parts.pop(0)
        if source_ports != "any" and not cls.is_numeric_port(source_ports):
            log(f"{source_ports=}", level=TRACE)
            raise ValueError(errormsg)
        if source_ports != "any":
            new_rule.sports = source_ports
        dest_addr = parts.pop(0)
        if not (dest_addr == "any" or cls.is_valid_ipv4(dest_addr) or cls.is_valid_ipv6(dest_addr)):
            log(f"{dest_addr=}", level=TRACE)
            raise ValueError(errormsg)
        if dest_addr != "any":
            new_rule.dest_addr = dest_addr
        dest_ports = parts.pop(0)
        if dest_ports != "any" and not cls.is_numeric_port(dest_ports):
            log(f"{dest_ports=}", level=TRACE)
            raise ValueError(errormsg)
        elif dest_ports != "any":
            new_rule.dports = dest_ports
        if new_rule.protocol not in ("any","both") and (new_rule.sports or new_rule.dports):
            try:
                new_rule.check_valid_port_protocol(new_rule.protocol)
            except ValueError:
                log(f"{new_rule.protocol=}", level=TRACE)
                raise ValueError(errormsg)
        if len(parts) == 3:
            sapp = parts.pop(0)
            if sapp != "-":
                new_rule.sapp = sapp
            dapp = parts.pop(0)
            if dapp != "-":
                new_rule.dapp = dapp
        elif len(parts) == 1:
            if "_" in parts[0]:
                direction,interface = parts.pop(0).split("_")
            else:
                direction,interface = parts.pop(0),""
            if direction not in ("in", "out"):
                log(f"{direction=}", level=TRACE)
                raise ValueError(errormsg)
            new_rule.direction = direction
            if interface:
                try:
                    cls.check_interface(interface)
                except ValueError:
                    log(f"{interface=}", level=TRACE)
                    raise ValueError(errormsg)
                if direction == "out":
                    new_rule.output_interface = interface
                else:
                    new_rule.input_interface = interface
        else:
            raise ValueError(errormsg)
        return new_rule

    def print_rule_ipt(self, silent=False) -> str:
        # print the rule as it is as an iptables rule or multiple rules as appropriate
        # for cases where "on" isn't specified, in order for the rule to actually account for -i vs -o, I need to either make a rule using a sensible default or make multiple rules covering all ins and outs (harder of course).
        # Rule context:
        # -A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN # Allow containers to reach out
        # -A DOCKER-USER -i docker0 -j RETURN # allow docker-internal comms part 1 (by interface)
        # -A DOCKER-USER -s 172.17.0.0/12 -j RETURN # allow docker-internal comms part 2 (by subnet)
        # append all other rules here
        # -A DOCKER-USER -j DROP # drop all other conns # This is the default action line. So it can be RETURN or DROP (allow or deny)
        # Form pattern: action[_logtype] protocol ipv_type source_addr source_ports dest_addr dest_ports [sapp dapp] direction[_interface] [comment]
        # [RULEFORM] allow tcp both any any any 8080 in
        # -A DOCKER-USER -i {default_iface} -m conntrack --ctorigdstport 8080 --ctdir ORIGINAL -p tcp -j RETURN
        # [RULEFORM] allow any ipv4 162.237.248.148 any 192.168.1.50 8080 in
        # -A DOCKER-USER -i {default_iface} -m conntrack --ctorigsrc 162.237.248.148 --ctorigdst 192.168.1.50 --ctorigdstport 8080 --ctdir ORIGINAL -p tcp -j RETURN
        # -A DOCKER-USER -i {default_iface} -m conntrack --ctorigsrc 162.237.248.148 --ctorigdst 192.168.1.50 --ctorigdstport 8080 --ctdir ORIGINAL -p udp -j RETURN
        rules = [f"-A {CHAIN} "]
        if self.direction == "out":
            rules[0] += "-o "
            if self.output_interface:
                rules[0] += f"{self.output_interface} "
            else:
                rules[0] += f"{DEFAULT_IFACE} "
                if not silent:
                    log(f"No output interface was provided (no \"on\" clause). Due to the implementation of the DOCKER-USER chain, the default interface to the internet ({DEFAULT_IFACE}) has been provisioned for this rule", level=WARNING)
        else:
            rules[0] += "-i "
            if self.input_interface:
                rules[0] += f"{self.input_interface} "
            elif not silent:
                log(f"No input interface was provided (no \"on\" clause). Due to the implementation of the DOCKER-USER chain, the default interface to the internet ({DEFAULT_IFACE}) has been provisioned for this rule", level=WARNING)
                rules[0] += f"{DEFAULT_IFACE} "
        rules[0] += "-m conntrack --ctdir ORIGINAL "
        if self.source_addr and self.source_addr != "any":
            rules[0] += f"--ctorigsrc {self.source_addr} "
        if self.dest_addr and self.dest_addr != "any":
            rules[0] += f"--ctorigdst {self.dest_addr} "
        if self.sports:
            if "," not in self.sports:
                rules[0] += f"--ctorigsrcport {self.sports} "
            else:
                raise ValueError("ctorigsrcport does not support csv for port ranges, only ranges using colon (:)")
        if self.dports:
            if "," not in self.dports:
                rules[0] += f"--ctorigdstport {self.dports} "
            else:
                raise ValueError("ctorigdstport does not support csv for port ranges, only ranges using colon (:)")
        if self.protocol == "both":
            rules.append(rules[0])
            rules[0] += "-p tcp "
            rules[1] += "-p udp "
        else:
            rules[0] += f"-p {self.protocol} "
        if self.action == "allow":
            action = "-j RETURN"
        elif self.action == "deny":
            action = "-j DROP"
        elif self.action == "reject":
            action = "-j REJECT"
        elif self.action == "limit":
            raise ValueError("limit action not implemented yet")
        for i in range(len(rules)):
            rules[i] += action
        return '\n'.join(f"{i}" for i in rules)

    def print_rule_dfw(self) -> str:
        # print the rule as it was entered in ufw-like syntax
        is_advanced = bool(self.input_interface or self.output_interface or self.source_addr or self.sports or self.dest_addr)
        action = self.action
        direction = self.direction
        if is_advanced:
            from_clause = ""
            to_clause = ""
            interface = self.input_interface if self.input_interface else self.output_interface
            if self.source_addr or self.sports:
                from_clause = f" from {self.source_addr if self.source_addr else 'any'}{' port '+self.sports if self.sports else ''}"
                if self.sapp:
                    from_clause += f" app {self.sapp}"
            if self.dest_addr or self.dports:
                to_clause = f" to {self.dest_addr if self.dest_addr else 'any'}{' port '+self.dports if self.dports else ''}"
                if self.dapp:
                    to_clause += f" app {self.dapp}"
            return f"{self.action} {self.direction} {'on '+interface if interface else ''}{self.log+' ' if self.log else ''}{from_clause}{to_clause}{'proto '+{self.protocol} if self.protocol not in ('both', 'any', '') else ''}"
        else:
            port_proto = self.dports
            if self.protocol in ("tcp", "udp"):
                port_proto += f"/{self.protocol}"
            return f"{self.action} {self.direction} {self.log+' ' if self.log else ''}{port_proto}"

    @staticmethod
    def get_applications() -> tuple[str]:
        # TODO implement some basic file-level validation logic here
        return (
                "ssh",
                "smtp",
                "tftp",
                "Socks",
                "PeopleNearby",
                "auth",
                "badApp"
                )

    def get_port_proto_from_app(self, app: str) -> (str, str):
        # TODO implement some validation logic here for the requested app
        if app == "Socks":
            return "100", "tcp"
        elif app == "PeopleNearby":
            return  "555", "udp"
        elif app == "ssh":
            return "22", "tcp"
        elif app == "badApp":
            return "101", "ipv6"
        elif app == "smtp":
            return "25", "tcp"
        else:
            return "000", "fake-proto"

    def push(self, is_dry) -> int:
        # This makes sends the Rule to iptables.
        cmd = ["iptables"] # need to construct the command based on defined members created in interpret or read
        cmd.extend(self.print_rule_ipt().split())
        if not len(cmd) > 2:
            return RULE_INVALID
        if not is_dry:
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                return result.returncode
            except subprocess.CalledProcessError as e:
                log(f"Command failed: {' '.join(cmd)}\nError: {e.stderr}", CRITICAL)
                return IPTABLES_ERROR
        else:
            log(f"iptables command would have been: {cmd}", level=INFO)
            return 0

def get_version_string() -> str:
    return f"{PROGRAM_NAME} version {VERSION}"

def log(*args, level=INFO, **kwargs):
    if level >= LOG_LEVEL:
        print(*args, **kwargs)

def write_config(config: str): # I can think of no case where I need to check for this failing. It should always succeed. PermissionError? I already check euid and verify/create the config at program startup...
    with open(CONFIG_PATH, "w") as conf:
        conf.write(config)

def read_config() -> str:
    try:
        with open(CONFIG_PATH, "r") as conf:
            return conf.read()
    except FileNotFoundError:
        log(f"config file does not exist at {CONFIG_PATH}. Making a new, blank config file.", level=INFO)
        write_config("")
        return ""

def is_config_valid(config: str) -> bool:
    # TODO
    # store states at the top of the config as comments. Like log enabled state and level.
    # ENABLED: True|False
    # DEFAULT: allow|deny
    # LOG: True|False
    # LOG_LEVEL: off|low|medium|high|full
    return True

def read_rules_file() -> (list[str], int):
    rules_list = []
    try:
        with open(DFW_RULES_PATH, "r") as rules_file:
            for line in rules_file.readlines():
                if line.startswith("[RULEFORM]"):
                    rules_list.append(line)
        log("Read rules file successfully", level=TRACE)
        return rules_list, 0
    except FileNotFoundError:
        log(f"Reading {DFW_RULES_PATH} failed due to missing file. Aborting!", level=CRITICAL)
        return [], FILE_MISSING

def write_rules_file(content: str, action: str) -> int:
    # rules should only consist of [RULEFORM]s and the associated iptable rule(s) for each form. The initial few lines of dfw.rules never change (store these in code), and the final line is determined by the value of default in dfw.conf.
    try:
        shutil.copy2(DFW_RULES_PATH, DFW_RULES_PATH+".bak")
        log("Made backup of dfw.rules.", level=DEBUG)
    except FileNotFoundError:
        log(f"Couldn't back up {DFW_RULES_PATH} due to missing file. Aborting!", level=CRITICAL)
        return FILE_MISSING
    with open(DFW_RULES_PATH, "w") as rules_file:
        rules_file.writelines(content)
    log("Wrote to dfw.rules.", level=DEBUG)
    print(action)

def request_confirmation(prompt: str) -> bool:
    while True:
        check = input(f"{prompt}\nProceed with operation (y|n)? ")
        if check.lower() == "y":
            return True
        elif check.lower() == "n":
            return False

def process_rule(new_rule: Rule, default="deny") -> (str,str,int):
    rules_str_list,check = read_rules_file()
    if check != 0:
        return "","",check
    rules = []
    for rule_str in rules_str_list:
        try:
            rule = Rule.parse_rule_form(rule_str)
        except ValueError as e:
            log(f"ERROR: {e} in {DFW_RULES_PATH}", level=ERROR)
            return "","",RULE_INVALID
        rules.append(rule)
    if new_rule.modification == "delete":
        if new_rule.delete_index:
            index = int(new_rule.delete_index)
            if len(rules) < 1 or len(rules) < index:
                log("Invalid rule index", level=ERROR)
                return "","",RULE_INVALID
            if request_confirmation(f"Deleting:\n {rules[index-1].print_rule_dfw()}") == True:
                del rules[index-1]
            else:
                return "","",CONFIRMATION_DENIED
        else:
            index = None
            check_vs = new_rule.print_rule_form()
            for i,rule in enumerate(rules):
                if check_vs == rule.print_rule_form():
                    index = i
                    break
            else:
                log("No rule matched input", level=ERROR)
                return "","",RULE_INVALID
            if request_confirmation(f"Deleting:\n {rules[index].print_rule_dfw()}") == True:
                del rules[index]
            else:
                return "","",CONFIRMATION_DENIED
        summary = "Rule deleted"
    elif new_rule.modification in ("insert","prepend"):
        index = 0 if new_rule.modification == "prepend" else int(new_rule.insert_index)
        rules.insert(index-1, new_rule)
        summary = "Rule added"
    else:
        check_vs = new_rule.print_rule_form()
        for i,rule in enumerate(rules):
            if check_vs == rule.print_rule_form():
                index = i
                log("Skipping adding existing rule", level=WARNING)
                return "","",RULE_INVALID
        rules.append(new_rule)
        summary = "Rule added"
    content = (
        f"# generated by {PROGRAM_NAME} version {VERSION}. Default={default}\n"
        f"{RULES_HEAD}\n"
        + '\n\n'.join(f"{rule.print_rule_form()}\n{rule.print_rule_ipt(True)}" for rule in rules)
        + (f"\n\n{RULES_TAIL_DENY}\n" if default=="deny" else f"\n\n{RULES_TAIL_ALLOW}\n")
    )
    return content,summary,0

def status_is_enabled() -> (bool, int):
    # This needs testing and refining. I want proper error handling if something is wrong in the command itself (using check=True) but I expect grep to return non-zero if dfw is disabled...
    # shell=True is a security risk, technically speaking but since no part of the input relies on user-input it should be okay.
    try:
        result = subprocess.run(f"iptables -S | grep -- '{RULE_COMMENT}'", shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
        return result.returncode == 0
    except Exception as e:
        print(f"Exception occurred: {e}")
        return False, 1

# I need to make sure that if docker restarts, this application detects that and re-applies the rules. docker restart flushes the DOCKER_USER chain, you see.
def push_rules_to_iptables(is_dry) -> int:
    # TODO read rules from dfw.rules, flush chain, and apply rules from dfw.rules.

    return 0

def check_rule_form_parsing(rule: Rule):
    ruleform = rule.print_rule_form()
    log(rule.print_rule_form.__doc__, level=DEBUG)
    log(ruleform, level=DEBUG)
    rule_vars = vars(rule)
    rerule_vars = vars(Rule.parse_rule_form(ruleform))
    log(rerule_vars, level=DEBUG)
    failures = ""
    for key,val in rerule_vars.items():
        if key in rule_vars.keys() and rule_vars[key] == val:
            continue
        failures += f"{key}: {val}\n"
    if failures:
        raise ValueError(f"Rule vs Rerule not a match:\n{failures[:-1]}")

def enable_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log(f"{args.dry_run=}", level=DEBUG)
    log(f"{args.config=}", level=DEBUG)
    if not args.dry_run:
        return push_rules_to_iptables()
    else:
        return 0

def disable_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log(f"{args.dry_run=}", level=DEBUG)
    log(f"{args.config=}", level=DEBUG)
    return remove_config_from_rules(args.dry_run)

def default_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    # default allow|deny|reject DIRECTION
    #        change the default policy for traffic going DIRECTION, where DIRECTION is one of incoming, outgoing or routed. Note
    #        that existing rules will have to be migrated manually when changing the default policy. See RULE SYNTAX for more on
    #        deny and reject.
    log(f"{args=}", level=TRACE
    log(f"{args.dry_run=}", level=DEBUG)
    log("This operation is not yet implemented", level=WARNING)
    return 0

def logging_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    # logging on|off|LEVEL
    #        toggle  logging.  Logged  packets use the LOG_KERN syslog facility. Systems configured for rsyslog support may also
    #        log to /var/log/ufw.log. Specifying a LEVEL turns logging on for the specified LEVEL.  The  default  log  level  is
    #        'low'.  See LOGGING for details.
    log(f"{args=}", level=TRACE
    log(f"{args.dry_run=}", level=DEBUG)
    log("This operation is not yet implemented", level=WARNING)
    return 0

def rule_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    # Example of blocking port 8080
    # :DOCKER-USER - [0:0]
    # -A DOCKER-USER -m conntrack --ctorigdstport 8080 -p tcp -j DROP
    # -A DOCKER-USER -m conntrack --ctorigdstport 8080 -p udp -j DROP
    # -A DOCKER-USER -j RETURN
    # Example of limit
    # :DOCKER-USER - [0:0]
    # -A DOCKER-USER -p tcp -m conntrack --ctorigdstport 8080 --ctstate NEW -m recent --set --name PORT8080
    # -A DOCKER-USER -p tcp -m conntrack --ctorigdstport 8080 --ctstate NEW -m recent --update --seconds 30 --hitcount 6 --name PORT8080 -j DROP
    # -A DOCKER-USER -j RETURN
    log(f"{args=}", level=TRACE)
    log(f"command and remainder are: {args.command}, {' '.join(remainder)}", level=TRACE)
    try:
        rule = Rule.parse_rule_command(f"{args.command} {' '.join(remainder)}")
    except ValueError as e:
        log(f"ERROR: {e}", level=ERROR)
        return 1
    log(vars(rule), level=DEBUG)
    if not rule.modification: # don't test on delete/insert/prepend rules
        check_rule_form_parsing(rule)
    if rule.action:
        log(f"{rule.print_rule_ipt(True)=}", level=DEBUG)
    # need to place the rule in the rule file then update the rules in iptables
    new_rules,summary,check = process_rule(rule, "deny") # TODO implement config checking to see if we are doing deny or allow as default
    if check != 0:
        return check
    if not args.dry_run:
        return write_rules_file(new_rules,summary)
    else:
        print(new_rules)
        return 0

def reload_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log("This operation is not yet implemented", level=WARNING)
    return 0

def reset_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log("This operation is not yet implemented", level=WARNING)
    return 0

def status_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log("This operation is not yet implemented", level=WARNING)
    return 0

def status_numbered_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log("This operation is not yet implemented", level=WARNING)
    return 0

def status_verbose_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log("This operation is not yet implemented", level=WARNING)
    return 0

def show_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE
    log("This operation is not yet implemented", level=WARNING)
    return 0

def version_func(args: argparse.Namespace, remainder: tuple[str]) -> int:
    log(f"{args=}", level=TRACE)
    print(get_version_string()) # print here because it should always show regardless of log level.
    return 0

def configure_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog=PROGRAM_NAME, description="CLI tool accepting ufw-like commands to modify ufw's after.rules file to support adding firewall rules that docker will respect.")
    parser.add_argument("-d", "--dry-run", action="store_true", help="Run using given input without making any change to the system. This also attempts to test the provided command for validity.")
    parser.add_argument("-v", "--verbose", action="count", default=0, help="Enable verbose logging (repeat up to 3x for increased verbosity).")
    parser.add_argument("-s", "--suppress", action="count", default=0, help="Suppress error messages (repeat up to 2x to suppress all messages")
    parser.add_argument("-V", "--version", action="version", version=get_version_string())

    subparsers = parser.add_subparsers(dest="command", required=True, help="Provide the command to run")

    enable_parser = subparsers.add_parser("enable", help="Adds previously defined rules to ufw's after.rules file.")
    enable_parser.set_defaults(func=enable_func)

    disable_parser = subparsers.add_parser("disable", help=f"Removes all rules added by {PROGRAM_NAME} from ufw's after.rules file.")
    disable_parser.set_defaults(func=disable_func)

    default_parser = subparsers.add_parser("default", help="")
    default_parser.set_defaults(func=default_func)

    logging_parser = subparsers.add_parser("logging", help="") # may be redundant with --verbose?
    logging_parser.set_defaults(func=logging_func)

    rule_parser = subparsers.add_parser("rule", help=f"Add a rule {PROGRAM_NAME}.")
    rule_parser.set_defaults(func=rule_func)

    allow_parser = subparsers.add_parser("allow", help=f"Adds an allow rule to ufw's after.rules file.")
    allow_parser.set_defaults(func=rule_func)

    deny_parser = subparsers.add_parser("deny", help="Adds a deny rule to ufw's after.rules file.")
    deny_parser.set_defaults(func=rule_func)

    reject_parser = subparsers.add_parser("reject", help="Adds a reject rule to ufw's after.rules file.")
    reject_parser.set_defaults(func=rule_func)

    limit_parser = subparsers.add_parser("limit", help="Adds a limit rule to ufw's after.rules file.")
    limit_parser.set_defaults(func=rule_func)

    delete_parser = subparsers.add_parser("delete", help="Deletes the specified rule from ufw's after.rules file.")
    delete_parser.set_defaults(func=rule_func)

    insert_parser = subparsers.add_parser("insert", help="")
    insert_parser.set_defaults(func=rule_func)

    prepend_parser = subparsers.add_parser("prepend", help="")
    prepend_parser.set_defaults(func=rule_func)

    reload_parser = subparsers.add_parser("reload", help=f"Removes and re-adds all {PROGRAM_NAME}-added rules from/to ufw's after.rules file, then reloads ufw.")
    reload_parser.set_defaults(func=reload_func)

    reset_parser = subparsers.add_parser("reset", help="")
    reset_parser.set_defaults(func=reset_func)

    status_parser = subparsers.add_parser("status", help=f"Prints all {PROGRAM_NAME}-added rules. Use {PROGRAM_NAME} status --help for more options.")
    status_parser.set_defaults(func=status_func)
    status_parser_subparsers = status_parser.add_subparsers(dest="", required=False)
    status_numbered_parser = status_parser_subparsers.add_parser("numbered", help=f"Prints all {PROGRAM_NAME}-added rules as a numbered list.")
    status_numbered_parser.set_defaults(func=status_numbered_func)
    status_verbose_parser = status_parser_subparsers.add_parser("verbose", help=f"Prints all {PROGRAM_NAME}-added rules with additional details.")
    status_verbose_parser.set_defaults(func=status_verbose_func)

    show_parser = subparsers.add_parser("show", help="")
    show_parser.set_defaults(func=show_func)

    version_parser = subparsers.add_parser("version", help=f"Print {PROGRAM_NAME} version info.")
    version_parser.set_defaults(func=version_func)

    return parser

def docker_user_chain_exists():
    try:
        result = subprocess.run(["iptables", "-L", "DOCKER-USER", "-n"])
        return result.returncode == 0
    except FileNotFoundError:
        return False

def main():
    parser = configure_parser()
    args,remainder = parser.parse_known_args()
    global LOG_LEVEL
    if args.verbose >= 3:
        LOG_LEVEL = TRACE
    elif args.verbose == 2:
        LOG_LEVEL = DEBUG
    elif args.verbose == 1:
        LOG_LEVEL = INFO
    elif args.suppress == 1:
        LOG_LEVEL = ERROR
    elif args.suppress >= 2:
        LOG_LEVEL = CRITICAL
    else:
        LOG_LEVEL = WARNING
    log(*sys.argv, level=DEBUG)
    #if not args.dry_run and os.geteuid() != 0:
    #    print(f"You need to be root to run this script")
    #    sys.exit(NOT_ROOT)
    #if not args.dry_run and not docker_user_chain_exists():
    #    print(f"The {CHAIN} chain does not exist in iptables or the iptables command doesn't exist. Ensure iptables and docker are correctly configured on your system.")
    if not os.path.exists(DFW_RULES_PATH):
        log(f"{DFW_RULES_PATH} doesn't exist. Aborting!", level=CRITICAL) # Don't need to abort. I can just create it.
        sys.exit(FILE_MISSING)
    args.config = read_config()
    sys.exit(args.func(args, remainder))

if __name__ == "__main__":
    main()
